# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            post |> blog
tagline:          
description:      
url:              
baseurl:          /

author:
  name:           'Jared Hester'
  url:            

paginate:         5

# Custom vars
version:         

github:
  repo:           


exclude: [  packages, cloudroutine.blog, tools, paket.*, 
            Gemfile.*, Gemfile, LICENSE.md,publish.bat, README.md ]